// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'location_report.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'location_report.g.dart';

@freezed
class LocationReport with _$LocationReport {
  const factory LocationReport({
    required DateTime timestamp,
    required String id,
    required double latitude,
    required double longitude,
    double? elevation,
    double? accuracy,
    double? heading,
    double? speed,
    //required int age,
  }) = _LocationReport;

  factory LocationReport.fromJson(Map<String, Object?> json) =>
      _$LocationReportFromJson(json);
}

@freezed
class AllLocationsReport with _$AllLocationsReport {
  @JsonSerializable(explicitToJson: true)
  factory AllLocationsReport({
    required DateTime timestamp,
    required Map<String, LocationReport> locations,
  }) = _AllLocationsReport;

  factory AllLocationsReport.fromJson(Map<String, Object?> json) =>
      _$AllLocationsReportFromJson(json);
}
